version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "3000:3000"  # external services port range
